### ISSUE TITLE
7.8.0-simd-avx2 fails to start: AttributeError: module 'PIL.ImageCms' has no attribute 'Flags'. Did you mean: 'flag'?

### ISSUE THREAD

**Issue by tchollingsworth** [MinimalCompact/thumbor#174]
The recent update to [7.8.0-simd-avx2](https://github.com/orgs/MinimalCompact/packages/container/thumbor/954393514?tag=7.8.0-simd-avx2) fails to start:

```
---> Starting thumbor with 4 processes...
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 5, in <module>
    from thumbor.server import main
  File "/usr/local/lib/python3.11/site-packages/thumbor/server.py", line 26, in <module>
    from thumbor.console import get_server_parameters
  File "/usr/local/lib/python3.11/site-packages/thumbor/console.py", line 13, in <module>
    from thumbor.context import ServerParameters
  File "/usr/local/lib/python3.11/site-packages/thumbor/context.py", line 13, in <module>
    from thumbor.metrics.logger_metrics import Metrics
  File "/usr/local/lib/python3.11/site-packages/thumbor/metrics/logger_metrics.py", line 11, in <module>
    from thumbor.utils import logger
  File "/usr/local/lib/python3.11/site-packages/thumbor/utils.py", line 37, in <module>
    _FLAGS = getattr(ImageCms, "FLAGS", ImageCms.Flags)
                                        ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageCms.py", line 128, in __getattr__
    raise AttributeError(msg)
AttributeError: module 'PIL.ImageCms' has no attribute 'Flags'. Did you mean: 'flag'?
```

<details>
<summary>docker-compose.yml</summary>

```
services:
  thumbor:
    image: ghcr.io/minimalcompact/thumbor:latest-simd-avx2
    env_file: thumbor.env
    volumes:
      - thumbor-data:/data
    restart: unless-stopped
```

</details>

<details>
<summary>thumbor.env</summary>

```
# VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
# but you usually need to point it to your domain, e.g. thumbor.example.com
VIRTUAL_HOST=subdomain.example.com
# THUMBOR_NUM_PROCESSES control how many processes run inside the container
# Normally this is set in connection with the number of CPU cores
# Note however that you can also use the docker-compose scale option to dynamically
# scale your thumbor instances
THUMBOR_NUM_PROCESSES=4
# this would allow CORS from any origin (you can restrict to specific origins if you want)
CORS_ALLOW_ORIGIN=*
# returns a webp image if browser Accept headers match
AUTO_WEBP=True
# nginx-proxy does caching automatically, so no need to store the result storage cache
# (this greatly speeds up and saves on CPU)
RESULT_STORAGE=thumbor.result_storages.no_storage
# RESULT_STORAGE_STORES_UNSAFE=True
# STORAGE=thumbor.storages.file_storage

SECURITY_KEY=some_s3cret
ALLOW_UNSAFE_URL=False
```

</details>

**Comment by toto4ds** [comment]
for 7.8.0-simd-sse4 too

**Comment by gingerlime** [comment]
This seems like an upstream issue, potentially introduced by https://github.com/thumbor/thumbor/pull/1788

#1788 fixed compatibility with Pillow 12, but the implementation is not compatible with older Pillow-compatible APIs such as pillow-SIMD 9.5.0.post2 (which is the latest version of pillow-SIMD), because `getattr(ImageCms, "FLAGS", ImageCms.Flags)` eagerly evaluates ImageCms.Flags

I would suggest you report this to the thumbor project directly.
